# Generated by Django 3.0.8 on 2020-07-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200719_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female')]),
        ),
    ]
