name: Testing 
on: push 

jobs:
  test_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install requirements.txt  
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: set Secret Key
      run: |
        echo "::set-env name=SECRET_KEY::${{ secrets.SECRET_KEY }}"
    - name: run django unit Testing
      run: |
        python manage.py test

        