name: Testing 
on: push 

jobs:
  test_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install requirements.txt  
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: set Secret Key
      run: |
        echo "::set-env name=SECRET_KEY::${{ secrets.SECRET_KEY }}"
        echo "::set-env name=EMAIL_PORT::${{ secrets.EMAIL_PORT }}"
        echo "::set-env name=EMAIL_HOST_USER::${{ secrets.EMAIL_HOST_USER }}"
        echo "::set-env name=EMAIL_HOST_PASSWORD::${{ secrets.EMAIL_HOST_PASSWORD }}"
        echo "::set-env name=EMAIL_HOST::${{ secrets.EMAIL_HOST }}"
        echo "::set-env name=AWS_STORAGE_BUCKET_NAME::${{ secrets.AWS_STORAGE_BUCKET_NAME }}"
        echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID }}"
    - name: run django unit Testing
      run: |
        python manage.py test

        
